version: '3.8'
services:
  nginx_server:
    image: nginx_todoist_server:latest
    build:
      context: ./nginx
      args:
        - DOMAIN
    container_name: nginx_server
    volumes:
      - ./nginx:/etc/nginx
      - /etc/letsencrypt:/etc/letsencrypt  # <--- Adjust this line
    ports:
      - "443:443"
    networks:
      - todoist_network
    depends_on:
      - webhook_app

  webhook_app:
    image: webhook_todoist_airtable_app:latest
    build:
      context: ./todoist-sync
    container_name: webhook_app
    ports:
      - 8000:8000
    volumes:
      - ./todoist-sync:/app
    command: ["python", "main.py"]
    env_file:
      - .env
    networks:
      - todoist_network

networks:
  todoist_network:
    driver: bridge
